project:
  type: book
  output-dir: docs

book:
  title: "Docs & Dev Log: Climate Knowledge Graph"
  author: 
  -  name: Simon Worthington
     orcid: 0000-0002-8579-9717
     email: simon.worthington@tib.eu
  -  name: Laura Oldenbourg
     orcid: 0009-0003-5070-0099
  date: today
  chapters:
    - index.qmd
    - roadmap.qmd
    - workflow.qmd
    - reports.qmd
    - styles.qmd
    - datamodels.qmd
    - ar6.qmd
    - data-imprint.qmd

  repo-url: https://github.com/TIBHannover/climate-knowledge-graph
  repo-actions: [issue]

format:
  html:
    theme: cosmo



