project:
  type: book
  output-dir: docs

book:
  title: "Documentation: Climate Knowledge Graph"
  author: 
  -  name: Simon Worthington
     orcid: 0000-0002-8579-9717
     email: simon.worthington@tib.eu
  -  name: Laura Oldenbourg
  date: today
  chapters:
    - index.qmd
    - roadmap.qmd
    - workflow.qmd
    - reports.qmd
    - datamodel.qmd
    - styles.qmd

  repo-url: https://github.com/TIBHannover/climate-knowledge-graph
  repo-actions: [issue]

format:
  html:
    theme: cosmo



