# About {.unnumbered}

The Climate Knowledge Graph (CKG) is a project to make a _knowledge graph_ of the open access parts of the 10,000 page [*IPCC Sixth Assessment Report (AR6)*](https://www.ipcc.ch/assessment-report/ar6/) corpus.

## Goal

The goal is to enable easier knowledge use from complex document corpus by: 

1. Making corpus search results available as multi-format publications, and 
2. enabling corpus data analysis by providing FAIR linked open data resources.

CKG uses open-source software and can be used on any document corpus.

```{dot}
graph CKG {
  layout=dot
  rankdir="LR"
  AR6 -- KG;
  KG -- Publishing;
  Publishing -- CLI;
  Publishing -- CMS;
  Publishing -- LLM;
  KG -- Data_Analysis;
}
//| label: ckg-system
//| fig-cap: "Climate Knowledge Graph system"
```

## About us 

TIB project team: Lead - Simon Worthington, e-mail: [simon.worthington@tib.eu](mailto:simon.worthington@tib.eu) and; publishing specialist - Laura Oldenbourg. With support from Markus Stocker, lead of Lab Knowledge Infrastructures.

CKG is an R\&D project hosted at [TIB](https://www.tib.eu/en) – Leibniz Information Centre for Science and Technology and organised in partnership with [\#semanticClimate](https://semanticclimate.github.io/p/en/) and the National Institute of Plant Genome Research (NIPGR) - India.

CKG is funded by [TIB](https://www.tib.eu/en) Innovationsfond.

## Licensing

Sofware: All software is Open Source Initiative (OSI) open-source license compliant. Copyright the Authors.

IPCC reports. This content is Open Access and distributed under the terms of the Creative Commons Attribution licence CC-BY-NC-ND 4.0 https://creativecommons.org/creativelicenses. Copyright Intergovernmental Panel on Climate Change. 



